# Site settings
# in the templates available like {{ site.myvariable }}.
title: Clean portfolio theme for Jekyll powered by Bootstrap 4.
mail: tg9688@naver.com
name: Lee Je Hun
headline: baseball, Throw and Hit
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "<font class="papago-parent"><font class="papago-source" style="display:none;"><!-- SnapWidget --> <iframe src="https://snapwidget.com/embed/841919" class="snapwidget-widget" allowtransparency="true" frameborder="0" scrolling="no" style="border:none; overflow:hidden; width:495px; height:330px"></iframe></font><!-- SnapWidget --> <iframe src="https://snapwidget.com/embed/841919" class="snapwidget-widget" allowtransparency="true" frameborder="0" scrolling="no" style="border:none; overflow:hidden; width:495px; height:330px"></iframe></font>" # the base hostname & protocol for your site
copyright: 2016 Whatever Company, Inc. All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
mail: tg9688@naver.com
number: 010-9623-9688


